from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src     = Split("""
                main.c
                mnt.c
                """)

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
