Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src     = Glob('*.c')

if rtconfig.PLATFORM == 'iar':
        src += Glob('*_iar.S')
elif rtconfig.PLATFORM == 'gcc':
        src += Glob('*_gcc.S')
elif rtconfig.PLATFORM == 'armcc':
        src += Glob('*_rvds.S')

group = DefineGroup('CPU', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
