# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Split('''
                board.c
                drv_uart.c
                drv_timer.c
                ''')

CPPPATH = [cwd]

if GetDepend('RT_USING_ADC'):
    src += ['drv_adc.c']

if GetDepend('RT_USING_CPUTIME'):
    src += ['drv_cputime.c']

if GetDepend('RT_USING_LWIP'):
    src += ['drv_emac.c']

if GetDepend('RT_USING_PIN'):
    src += ['drv_gpio.c']

if GetDepend('RT_USING_HWTIMER'):
    src += ['drv_hwtimer.c']
    
if GetDepend('RT_USING_I2C'):
    src += ['drv_i2c.c']

if GetDepend('PKG_USING_GUIENGINE'):
    src += ['drv_lcd.c']

if GetDepend('RT_USING_PWM'):
    src += ['drv_pwm.c']

if GetDepend('RT_USING_RTC'):
    src += ['drv_rtc.c']

if GetDepend('RT_USING_SDIO'):
    src += ['drv_sdio.c']

if GetDepend('RT_USING_SPI'):
    src += ['drv_spi.c']

if GetDepend('RT_USING_WDT'):
    src += ['drv_wdt.c']

if GetDepend(['RT_USING_WIFI']):
    src += ['drv_wlan.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
